### ISSUE TITLE
Not receiving sharp rock

### ISSUE THREAD

**Issue by ivangeevo** [FrozenRainDev/hardcore-survival#1]
I tried smashing rocks onto stone and I get the successful message, but no sharp rocks are given to the player.

**Comment by FrozenRainDev** [comment]
The sharp rocks may fell into the hollow opposite the of stone. I'll fix this bug. If you still cannot find sharp rocks, please tell me.

**Comment by FrozenRainDev** [comment]
Now you can redownload the mod from Modrinth. Have a good time!
